# Generated by Django 6.0.1 on 2026-01-30 12:19

import django.db.models.deletion
import institucional.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Área de atuação')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Área de atuação',
                'verbose_name_plural': 'Áreas de atuação',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome da tag')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=institucional.models.blog_cover_upload_to, verbose_name='Imagem de capa')),
                ('summary', models.CharField(blank=True, max_length=160, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=12, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='institucional.areaofpractice', verbose_name='Área de atuação')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='institucional.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post do blog',
                'verbose_name_plural': 'Posts do blog',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='institucion_status_3e1b2a_idx')],
            },
        ),
    ]
